package devlab.hotel;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.util.List;
import java.util.Map;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Equipo
 */
public class AReservas extends javax.swing.JFrame implements ICardGenerator {
    private DBConnection conn;
    private java.time.LocalDate fechaInicio;
    private java.time.LocalDate fechaFin;
    private long cantidadDias;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AReservas.class.getName());

    /**
     * Creates new form AReservas
     */
    public AReservas() {
    this.conn = new DBConnection();
    initComponents(); 

    Cards.setLayout(new BoxLayout(Cards, BoxLayout.Y_AXIS));
    Cards.setAutoscrolls(true); 
    jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS); 
    configurarEventos();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        valorFechaI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        valorCantPersonas = new javax.swing.JTextField();
        valorFechaF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnBuscarHabitacion = new javax.swing.JButton();
        Habitaciones1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cards = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(160, 175, 185));

        btnAtras.setBackground(new java.awt.Color(160, 175, 185));
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 225, 220)));
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.setLabel("Atras");
        btnAtras.setPreferredSize(new java.awt.Dimension(29, 30));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 570, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(217, 217, 217));
        jPanel2.setPreferredSize(new java.awt.Dimension(199, 290));

        valorFechaI.setPreferredSize(new java.awt.Dimension(100, 24));
        valorFechaI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorFechaIActionPerformed(evt);
            }
        });

        jLabel1.setText("Personas");
        jLabel1.setToolTipText("");

        jLabel2.setText("Fecha inicio");

        valorCantPersonas.setPreferredSize(new java.awt.Dimension(100, 24));
        valorCantPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorCantPersonasActionPerformed(evt);
            }
        });

        valorFechaF.setPreferredSize(new java.awt.Dimension(100, 24));
        valorFechaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorFechaFActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha fin");

        btnBuscarHabitacion.setText("Buscar");
        btnBuscarHabitacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHabitacionActionPerformed(evt);
            }
        });

        Habitaciones1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Habitaciones1.setText("Buscar habitación");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(24, 24, 24))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valorCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnBuscarHabitacion))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Habitaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Habitaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(valorCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(valorFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarHabitacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Cards.setBackground(new java.awt.Color(217, 217, 217));
        Cards.setPreferredSize(new java.awt.Dimension(437, 255));

        javax.swing.GroupLayout CardsLayout = new javax.swing.GroupLayout(Cards);
        Cards.setLayout(CardsLayout);
        CardsLayout.setHorizontalGroup(
            CardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );
        CardsLayout.setVerticalGroup(
            CardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(Cards);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void configurarEventos() {
        btnBuscarHabitacion.addActionListener(e -> buscarHabitaciones());
    }
    
    @Override
    public JPanel crearCard(Map<String, Object> datos, boolean conBoton, String textoBoton) {
        JPanel card = crearBaseCard();
        
        JPanel content = new JPanel();
        content.setLayout(new BoxLayout(content, BoxLayout.Y_AXIS));
        content.setOpaque(false);

        int id = (int) datos.get("id");
        int capacidad = (int) datos.get("Cantidad_personas");
        float precioNoche = ((Float) datos.get("Precio_noche"));
        float precioTotal = precioNoche * cantidadDias;
        int cDoble = (int) datos.get("C_doble");
        int cSimple = (int) datos.get("C_simple");

        content.add(new JLabel("Capacidad: " + capacidad));
        content.add(new JLabel("Precio por noche: $" + precioNoche));
        content.add(new JLabel("Precio total: $" + precioTotal));
        content.add(new JLabel("Camas dobles: " + cDoble));
        content.add(new JLabel("Camas simples: " + cSimple));

        if (conBoton) {
            JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
            buttonPanel.setOpaque(false);
            JButton reservarBtn = new JButton(textoBoton);
            reservarBtn.setFont(new java.awt.Font("Segoe UI", 0, 10));
            reservarBtn.addActionListener(e -> reservarHabitacion(id, precioTotal));
            buttonPanel.add(reservarBtn);
            content.add(buttonPanel);
        }

        card.add(content, BorderLayout.CENTER);
        return card;
    }

    @Override
    public JPanel crearCard(Map<String, Object> datos) {
        return crearCard(datos, true, "Reservar");
    }

    private void buscarHabitaciones() {
        try {
            int cantPersonas = Integer.parseInt(valorCantPersonas.getText().trim());
            fechaInicio = java.time.LocalDate.parse(valorFechaI.getText().trim());
            fechaFin = java.time.LocalDate.parse(valorFechaF.getText().trim());

            cantidadDias = java.time.temporal.ChronoUnit.DAYS.between(fechaInicio, fechaFin);
            if (cantidadDias <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "La fecha de fin debe ser posterior a la de inicio.");
                return;
            }

            List<Map<String, Object>> disponibles = conn.ObtenerHabitacionesDisponiblesPorCapacidadYFecha(cantPersonas, fechaInicio, fechaFin);
            
            containerCards(disponibles, Cards, true, "Reservar");
            
        } catch (NumberFormatException | java.time.format.DateTimeParseException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese valores válidos (fechas en formato YYYY-MM-DD).");
        }
    }

    
    private void reservarHabitacion(int idHabitacion, float precioTotal) {
        DatosCliente datosCliente = new DatosCliente(conn, idHabitacion, fechaInicio, fechaFin, cantidadDias, precioTotal);

        JDialog dialog = new JDialog();
        dialog.setModal(true);
        dialog.setTitle("Datos del Cliente");
        dialog.setContentPane(datosCliente.getContentPane());
        dialog.pack();
        dialog.setLocationRelativeTo(this);

        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                buscarHabitaciones();
                JOptionPane.showMessageDialog(AReservas.this, 
                    "¡Reserva completada! Listado actualizado.", 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);
            }
        });

        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        dialog.setVisible(true);
        dialog.dispose();
    }



    private void valorFechaIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorFechaIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorFechaIActionPerformed

    private void valorCantPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorCantPersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorCantPersonasActionPerformed

    private void valorFechaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorFechaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorFechaFActionPerformed

    private void btnBuscarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHabitacionActionPerformed
        buscarHabitaciones(); 
    }//GEN-LAST:event_btnBuscarHabitacionActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.dispose();
        
        AdministradorFrame AdminFrame = new AdministradorFrame();
        AdminFrame.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> {
            DBConnection conn = new DBConnection();
            new AReservas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cards;
    private java.awt.Label Habitaciones1;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscarHabitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField valorCantPersonas;
    private javax.swing.JTextField valorFechaF;
    private javax.swing.JTextField valorFechaI;
    // End of variables declaration//GEN-END:variables
}
