/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package devlab.hotel;

import java.util.List;
import java.util.Map;
import javax.swing.BoxLayout;

/**
 *
 * @author Equipo
 */
public class AReservas extends javax.swing.JFrame {
    private DBConnection conn;
    private Clientes cliente;
    private java.time.LocalDate fechaInicio;
    private java.time.LocalDate fechaFin;
    private long cantidadDias;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AReservas.class.getName());

    /**
     * Creates new form AReservas
     */
    public AReservas() {
    this.conn = new DBConnection();
    this.cliente = new Clientes(conn, new java.util.Scanner(System.in)); 
    initComponents(); // ✅ PRIMERO CREÁS LOS COMPONENTES

    Cards.setLayout(new BoxLayout(Cards, BoxLayout.Y_AXIS)); // ✅ Ahora sí existe
    Cards.setAutoscrolls(true); 
    jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS); // Opcional
    configurarEventos();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        valorFechaI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        valorCantPersonas = new javax.swing.JTextField();
        valorFechaF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnBuscarHabitacion = new javax.swing.JButton();
        Habitaciones1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cards = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(160, 175, 185));

        btnAtras.setBackground(new java.awt.Color(160, 175, 185));
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 225, 220)));
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.setLabel("Atras");
        btnAtras.setPreferredSize(new java.awt.Dimension(29, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 570, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(217, 217, 217));
        jPanel2.setPreferredSize(new java.awt.Dimension(199, 290));

        valorFechaI.setPreferredSize(new java.awt.Dimension(100, 24));
        valorFechaI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorFechaIActionPerformed(evt);
            }
        });

        jLabel1.setText("Personas");
        jLabel1.setToolTipText("");

        jLabel2.setText("Fecha inicio");

        valorCantPersonas.setPreferredSize(new java.awt.Dimension(100, 24));
        valorCantPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorCantPersonasActionPerformed(evt);
            }
        });

        valorFechaF.setPreferredSize(new java.awt.Dimension(100, 24));
        valorFechaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorFechaFActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha fin");

        btnBuscarHabitacion.setText("Buscar");
        btnBuscarHabitacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHabitacionActionPerformed(evt);
            }
        });

        Habitaciones1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Habitaciones1.setText("Buscar habitación");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(24, 24, 24))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valorCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnBuscarHabitacion))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Habitaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Habitaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(valorCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(valorFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarHabitacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Cards.setBackground(new java.awt.Color(217, 217, 217));
        Cards.setPreferredSize(new java.awt.Dimension(437, 255));

        javax.swing.GroupLayout CardsLayout = new javax.swing.GroupLayout(Cards);
        Cards.setLayout(CardsLayout);
        CardsLayout.setHorizontalGroup(
            CardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );
        CardsLayout.setVerticalGroup(
            CardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(Cards);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void configurarEventos() {
        btnBuscarHabitacion.addActionListener(e -> buscarHabitaciones());
    }
    
    private void buscarHabitaciones() {
        try {
            int cantPersonas = Integer.parseInt(valorCantPersonas.getText().trim());
            fechaInicio = java.time.LocalDate.parse(valorFechaI.getText().trim());
            fechaFin = java.time.LocalDate.parse(valorFechaF.getText().trim());

            cantidadDias = java.time.temporal.ChronoUnit.DAYS.between(fechaInicio, fechaFin);
            if (cantidadDias <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "La fecha de fin debe ser posterior a la de inicio.");
                return;
            }

            List<Map<String, Object>> disponibles = conn.ObtenerHabitacionesDisponiblesPorCapacidadYFecha(cantPersonas, fechaInicio, fechaFin);
            Cards.removeAll(); // Limpiar resultados previos

            if (disponibles.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "No hay habitaciones disponibles.");
            } else {
                for (Map<String, Object> hab : disponibles) {
                    Cards.add(crearCardHabitacion(hab));
                }
            }

            Cards.setPreferredSize(new java.awt.Dimension(Cards.getWidth(), Cards.getComponentCount() * 140));
            Cards.revalidate();
            Cards.repaint();
            
            

        } catch (NumberFormatException | java.time.format.DateTimeParseException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese valores válidos (fechas en formato YYYY-MM-DD).");
        }
    }
    
    private javax.swing.JPanel crearCardHabitacion(Map<String, Object> hab) {
        javax.swing.JPanel card = new javax.swing.JPanel(new java.awt.BorderLayout(10, 10));
        card.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5),
            javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY)
        ));
        card.setPreferredSize(new java.awt.Dimension(500, 130));

        try {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("img/habitacion.jpg"));
            java.awt.Image scaledImg = icon.getImage().getScaledInstance(120, 130, java.awt.Image.SCALE_SMOOTH); 
            javax.swing.JLabel imgLabel = new javax.swing.JLabel(new javax.swing.ImageIcon(scaledImg));
            card.add(imgLabel, java.awt.BorderLayout.WEST);
        } catch (Exception ex) {
            System.err.println("No se pudo cargar la imagen: " + ex.getMessage());
        }

        javax.swing.JPanel content = new javax.swing.JPanel();
        content.setLayout(new javax.swing.BoxLayout(content, javax.swing.BoxLayout.Y_AXIS));
        content.setOpaque(false);

        int id = (int) hab.get("id");
        int capacidad = (int) hab.get("Cantidad_personas");
        float precioNoche = ((Float) hab.get("Precio_noche"));
        float precioTotal = precioNoche * cantidadDias;
        int cDoble = (int) hab.get("C_doble");
        int cSimple = (int) hab.get("C_simple");

        content.add(new javax.swing.JLabel("Capacidad: " + capacidad));
        content.add(new javax.swing.JLabel("Precio por noche: $" + precioNoche));
        content.add(new javax.swing.JLabel("Precio total: $" + precioTotal));
        content.add(new javax.swing.JLabel("Camas dobles: " + cDoble));
        content.add(new javax.swing.JLabel("Camas simples: " + cSimple));

        javax.swing.JPanel buttonPanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        buttonPanel.setOpaque(false);
        javax.swing.JButton reservarBtn = new javax.swing.JButton("Reservar");
        reservarBtn.setFont(new java.awt.Font("Segoe UI", 0, 10));
        reservarBtn.addActionListener(e -> reservarHabitacion(id, precioTotal));
        buttonPanel.add(reservarBtn);

        content.add(buttonPanel); 

        card.add(content, java.awt.BorderLayout.CENTER);

        return card;
    }


    
    private void reservarHabitacion(int idHabitacion, float precioTotal) {
        int DNI = cliente.SolicitarDatosCliente(); // Método ya existente
        conn.InsertarReserva(idHabitacion, fechaInicio.toString(), fechaFin.toString(), (int) cantidadDias, precioTotal, DNI);
        javax.swing.JOptionPane.showMessageDialog(this, "Reserva realizada con éxito.");
    }



    private void valorFechaIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorFechaIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorFechaIActionPerformed

    private void valorCantPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorCantPersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorCantPersonasActionPerformed

    private void valorFechaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorFechaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorFechaFActionPerformed

    private void btnBuscarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHabitacionActionPerformed
        buscarHabitaciones(); 
    }//GEN-LAST:event_btnBuscarHabitacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> {
            DBConnection conn = new DBConnection();
            new AReservas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cards;
    private java.awt.Label Habitaciones1;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscarHabitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField valorCantPersonas;
    private javax.swing.JTextField valorFechaF;
    private javax.swing.JTextField valorFechaI;
    // End of variables declaration//GEN-END:variables
}
