package devlab.hotel;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Equipo
 */
public class EliminarReservasFrame extends javax.swing.JFrame implements ICardGenerator {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EliminarReservasFrame.class.getName());
    private DBConnection conn;
    private String tipo;
    private Boolean edicion;

    public EliminarReservasFrame(DBConnection conn, String tipo, Boolean edicion) {
        this.conn = conn;
        this.tipo = tipo;
        this.edicion = edicion;
        initComponents();
        Cards.setLayout(new javax.swing.BoxLayout(Cards, javax.swing.BoxLayout.Y_AXIS));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cards = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnBuscarReservas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(160, 175, 185));

        btnAtras.setBackground(new java.awt.Color(160, 175, 185));
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 225, 220)));
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.setLabel("Atras");
        btnAtras.setPreferredSize(new java.awt.Dimension(29, 30));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Cards.setBackground(new java.awt.Color(217, 217, 217));
        Cards.setForeground(new java.awt.Color(255, 255, 255));
        Cards.setPreferredSize(new java.awt.Dimension(437, 255));

        javax.swing.GroupLayout CardsLayout = new javax.swing.GroupLayout(Cards);
        Cards.setLayout(CardsLayout);
        CardsLayout.setHorizontalGroup(
            CardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );
        CardsLayout.setVerticalGroup(
            CardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(Cards);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel1.setText("Ingrese el DNI para buscar la Reserva");

        btnBuscarReservas.setBackground(new java.awt.Color(160, 175, 185));
        btnBuscarReservas.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarReservas.setText("Buscar");
        btnBuscarReservas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 225, 220)));
        btnBuscarReservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarReservas.setPreferredSize(new java.awt.Dimension(29, 30));
        btnBuscarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarReservasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscarReservas, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        if("admin".equals(tipo)) {
            AdministradorFrame AdminFrame = new AdministradorFrame();
            AdminFrame.setVisible(true);
        } else {
            ClienteFrame clFrame = new ClienteFrame();
            clFrame.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnBuscarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarReservasActionPerformed
        Cards.setLayout(new javax.swing.BoxLayout(Cards, javax.swing.BoxLayout.Y_AXIS));
        containerCards();
    }//GEN-LAST:event_btnBuscarReservasActionPerformed

    private void containerCards() {
        String dniTexto = jTextField1.getText();
        int dni;

        try {
            dni = Integer.parseInt(dniTexto);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "DNI inválido. Ingrese solo números.");
            return;
        }

        List<Map<String, Object>> disponibles = conn.obtenerReservasPorDNI(dni);
        containerCards(disponibles, Cards, true, edicion == true ? "Editar" : "Eliminar");
    }
    
    @Override
    public JPanel crearCard(Map<String, Object> datos, boolean conBoton, String textoBoton) {
        JPanel card = crearBaseCard();
        JPanel content = new JPanel();
        content.setLayout(new BoxLayout(content, BoxLayout.Y_AXIS));
        content.setOpaque(false);

        int ID = (int) datos.get("id_reserva");
        var fecha = datos.get("fecha_inicio");
        int ID_habitacion = (int) datos.get("id_habitacion");
        
        content.add(new JLabel("Fecha de inicio: " + fecha));
        content.add(new JLabel("Fecha de fin: " + datos.get("fecha_fin")));
        content.add(new JLabel("Cantidad de dias: " + datos.get("Cantidad_dias")));
        content.add(new JLabel("Precio total: $" + datos.get("Precio_total")));
        content.add(new JLabel("DNI del cliente: " + datos.get("DNI_cliente")));
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        
        try {
            LocalDate hoy = LocalDate.now();
            LocalDate fechaInicio = LocalDate.parse((CharSequence) fecha, formatter);

            if (conBoton) {
                JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
                buttonPanel.setOpaque(false);
                JButton eliminarEditarBtn = new JButton(textoBoton);
                eliminarEditarBtn.setFont(new java.awt.Font("Segoe UI", 0, 10));
                if("Eliminar".equals(textoBoton)) {
                    eliminarEditarBtn.addActionListener(e -> {
                        if (!fechaInicio.isAfter(hoy)) {
                            JOptionPane.showMessageDialog(this, "La reserva ya está en curso, no puede ser eliminada o cancelada");
                        } else {
                            conn.EliminarReserva(ID);
                            JOptionPane.showMessageDialog(this, "Se Eliminó correctamente su reserva");
                            containerCards();
                        }
                    });
                } else {
                    eliminarEditarBtn.addActionListener(e -> {
                        if (!fechaInicio.isAfter(hoy)) {
                            JOptionPane.showMessageDialog(this, "La reserva ya está en curso, no puede ser editar");
                        } else {
                            EditarReservaFrame editarReserva = new EditarReservaFrame(tipo,ID,ID_habitacion);
                            editarReserva.setVisible(true);
                            containerCards();
                        }
                    });
                }
                
                buttonPanel.add(eliminarEditarBtn);
                content.add(buttonPanel); 
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha inválido.");
        }

        card.add(content, BorderLayout.CENTER);
        return card;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cards;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscarReservas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
