/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package devlab.hotel;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Equipo
 */
public class EliminarReservasFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EliminarReservasFrame.class.getName());

    /**
     * Creates new form EliminarReservasFrame
     */
    private DBConnection conn;

    public EliminarReservasFrame(DBConnection conn) {
        this.conn = conn;
        initComponents();
        Cards.setLayout(new javax.swing.BoxLayout(Cards, javax.swing.BoxLayout.Y_AXIS));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cards = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnBuscarReservas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 300));

        jPanel1.setBackground(new java.awt.Color(160, 175, 185));

        btnAtras.setBackground(new java.awt.Color(160, 175, 185));
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 225, 220)));
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.setLabel("Atras");
        btnAtras.setPreferredSize(new java.awt.Dimension(29, 30));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 520, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Cards.setBackground(new java.awt.Color(217, 217, 217));
        Cards.setForeground(new java.awt.Color(255, 255, 255));
        Cards.setPreferredSize(new java.awt.Dimension(437, 255));

        javax.swing.GroupLayout CardsLayout = new javax.swing.GroupLayout(Cards);
        Cards.setLayout(CardsLayout);
        CardsLayout.setHorizontalGroup(
            CardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );
        CardsLayout.setVerticalGroup(
            CardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(Cards);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel1.setText("Ingrese el DNI para buscar la Reserva");

        btnBuscarReservas.setBackground(new java.awt.Color(160, 175, 185));
        btnBuscarReservas.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarReservas.setText("Buscar");
        btnBuscarReservas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 225, 220)));
        btnBuscarReservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarReservas.setPreferredSize(new java.awt.Dimension(29, 30));
        btnBuscarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarReservasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscarReservas, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(0, 238, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(44, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.dispose();

        AdministradorFrame AdminFrame = new AdministradorFrame();
        AdminFrame.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnBuscarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarReservasActionPerformed
        Cards.setLayout(new javax.swing.BoxLayout(Cards, javax.swing.BoxLayout.Y_AXIS));
        containerCards();
    }//GEN-LAST:event_btnBuscarReservasActionPerformed

    private void containerCards() {
        String dniTexto = jTextField1.getText();
        int dni;

        try {
            dni = Integer.parseInt(dniTexto);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "DNI inválido. Ingrese solo números.");
            return;
        }

        List<Map<String, Object>> disponibles = conn.ObtenerReservasPorDNI(dni);
        
        Cards.removeAll();

            if (disponibles.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "No hay habitaciones disponibles.");
            } else {
                for (Map<String, Object> hab : disponibles) {
                    Cards.add(crearCardReserva(hab));
                }
            }

            Cards.setPreferredSize(new java.awt.Dimension(Cards.getWidth(), Cards.getComponentCount() * 140));
            Cards.revalidate();
            Cards.repaint();
        
    }
    
    private javax.swing.JPanel crearCardReserva(Map<String, Object> hab) {
        javax.swing.JPanel card = new javax.swing.JPanel(new java.awt.BorderLayout(10, 10));
        card.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5),
            javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY)
        ));
        card.setPreferredSize(new java.awt.Dimension(500, 130));

        try {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("img/habitacion.jpg"));
            java.awt.Image scaledImg = icon.getImage().getScaledInstance(120, 130, java.awt.Image.SCALE_SMOOTH); 
            javax.swing.JLabel imgLabel = new javax.swing.JLabel(new javax.swing.ImageIcon(scaledImg));
            card.add(imgLabel, java.awt.BorderLayout.WEST);
        } catch (Exception ex) {
            System.err.println("No se pudo cargar la imagen: " + ex.getMessage());
        }

        javax.swing.JPanel content = new javax.swing.JPanel();
        content.setLayout(new javax.swing.BoxLayout(content, javax.swing.BoxLayout.Y_AXIS));
        content.setOpaque(false);
        int ID = (int) hab.get("id_reserva");
        var fecha = hab.get("fecha_inicio");
        content.add(new JLabel("ID de reserva: " + ID));
        content.add(new JLabel("ID de habitación: " + hab.get("id_habitacion")));
        content.add(new JLabel("Fecha de inicio: " + fecha));
        content.add(new JLabel("Fecha de fin: " + hab.get("fecha_fin")));
        content.add(new JLabel("Cantidad de dias: " + hab.get("cantidad_dias")));
        content.add(new JLabel("Precio total: " + hab.get("Precio_total")));
        content.add(new JLabel("DNI del cliente: " + hab.get("DNI_cliente")));

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        
        try {
            LocalDate hoy = LocalDate.now();
            LocalDate fechaInicio = LocalDate.parse((CharSequence) fecha, formatter);

            javax.swing.JPanel buttonPanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
            buttonPanel.setOpaque(false);
            javax.swing.JButton reservarBtn = new javax.swing.JButton("Eliminar reserva");
            reservarBtn.setFont(new java.awt.Font("Segoe UI", 0, 10));
            reservarBtn.addActionListener(e -> {
                if (!fechaInicio.isAfter(hoy)) {
                    javax.swing.JOptionPane.showMessageDialog(this, "La reserva ya está en curso, no puede ser eliminada o cancelada");
                } else {
                    conn.EliminarReserva(ID);
                    javax.swing.JOptionPane.showMessageDialog(this, "Se Eliminó correctamente su reserva");
                    containerCards();
                }
            });
            buttonPanel.add(reservarBtn);
            content.add(buttonPanel); 
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Formato de fecha inválido.");
        }

        card.add(content, java.awt.BorderLayout.CENTER);

        return card;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        new EliminarReservasFrame(new DBConnection()).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cards;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscarReservas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
